Preserve data
LoviMadaan/My-Portfolio-desktop-version pull request #8
Opened 2023-02-10 14:20 UTC by LoviMadaan

### In this branch
- We have added the javascript codes for preserving data in the local storage.

2023-02-10 15:10 UTC, Qoosim reviewed
#  *Status: Invalid Request* :red_circle: 

Hi @team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that 

- [ ] has some missing headings in your README file. Such headings like `Key Features` and `Future Features`. Kindly add those missing headings and their appropriate information under each of them.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-02-10 15:42 UTC, roshan-bajgain requested changes
Hi @LoviMadaan, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️
- Professional README file. ✔️

## Required Changes ♻️
- [ ] I cannot leave the comment there so I am leaving it here. Please implement so
- [ ] After filling the form, and not submitting it, the entered values should be saved in the browser. But in yours when I submit the form then only the date is saving on local storage. Please fix it
### Error
![his](https://user-images.githubusercontent.com/81727988/218132287-cd460191-615c-421a-afe2-81581d661a70.png)
- [ ] When the user changes the content of any input field, the data is saved to the local storage without sending it. please fix it
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-10 19:40 UTC, nicupop729 commented
This PR under a Second Opinion Review.

2023-02-10 20:02 UTC, nicupop729 reviewed
Hello @LoviMadaan & @Atril33  👋,

_This is an additional review as a result of the second opinion request._

Kudos for the good work you have done until now! :clap:

I noticed that the data is saved in the local storage and that after submitting the form, the inputs fields are populated with data from the local storage. That's very nice.

Only that one important project requirement was not followed: "When the user changes the content of any input field, the data is saved to the local storage." This means that when the user change the content of the text in the fields, it should be reflected instantly in the local storage and not only after submitting the form.
The form shouldn't be to be submitted for the input fields text to be saved in the local storage.

After implementing this project requirement too, kindly ask for another review in the dashboard.

Good luck and Keep rocking :four_leaf_clover:  🚀!

2023-02-11 05:00 UTC, Tadesse-Alemayehu approved these changes
### Hi @Atril33 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![barly](https://user-images.githubusercontent.com/69077061/218240992-73fecb9d-10ca-4238-b789-3214e4822f5d.gif)


## Highlights
 - [ ] Good job making the changes requested by the previous code reviewers. ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-11 05:00 UTC, TadesseDev commented on script.js
>      error.textContent = 'Please, all email characters should be lowercase';
- [Optional] Dear @LoviMadaan, I noticed you use on change event for the form, This is good but not the optimal solution. Please use `onInput` event instead of `onChange`, The difference is that the `oninput` event occurs immediately after the value of an element has changed, while `onchange` occurs when the element loses focus after the content has been changed. I hope you will make the changes.

2023-02-11 05:19 UTC, merged